# -*- coding: utf-8 -*-
"""Rellena las traducciones al inglés en app/i18n/cosechamedia_en.ts.

Uso: python tools/translate_en.py
"""
import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS_PATH = os.path.join(ROOT, "app", "i18n", "cosechamedia_en.ts")

TRANSLATIONS = {
    "Ingesta Completada": "Ingest Complete",
    "Ingesta con errores": "Ingest with errors",
    "Proyecto:": "Project:",
    "Actualizar proyectos": "Refresh projects",
    "Nuevo proyecto": "New project",
    "Eliminar proyecto": "Delete project",
    "Renombrar proyecto": "Rename project",
    "Duplicar proyecto": "Duplicate project",
    "Cambiar ruta maestra del proyecto": "Change project master path",
    "Configuración": "Settings",
    "Listo": "Ready",
    "Orígenes:": "Sources:",
    "E:\\DCIM...": "E:\\DCIM...",
    "Examinar": "Browse",
    "Ruta de origen": "Source path",
    "Cámara": "Camera",
    "⟳ Detectar": "⟳ Detect",
    "Detectar unidades extraíbles": "Detect removable drives",
    "Modo guiado": "Guided mode",
    "Asistente guiado para volcados rápidos (próximamente)": "Guided assistant for quick dumps (coming soon)",
    "📷 Escanear cámaras": "📷 Scan cameras",
    "Escanear cámaras de todos los orígenes checkeados": "Scan cameras from all checked sources",
    "Sesiones:": "Sessions:",
    "Nueva sesión": "New session",
    "Eliminar sesión": "Delete session",
    "Examinar origen de sesión…": "Browse session source…",
    "Destino:": "Destination:",
    "Por defecto": "Default",
    "Personalizado": "Custom",
    "Ruta...": "Path...",
    "Examinar...": "Browse...",
    "Modo delicado": "Delicate mode",
    "INICIAR INGESTA": "START INGEST",
    "DETENER": "STOP",
    "%v / %m archivos": "%v / %m files",
    "Generar proxies": "Generate proxies",
    "Genera proxies de los clips de video tras la ingesta": "Generate proxies of video clips after ingest",
    "0 procesados": "0 processed",
    "0 pendientes": "0 pending",
    "0 errores": "0 errors",
    "Reorganizar por metadatos": "Reorganize by metadata",
    "Reorganiza los archivos en 'Unknown_Camera' detectando su cámara por metadatos": "Reorganize files in 'Unknown_Camera' by detecting their camera via metadata",
    "Formatear orígenes al acabar:": "Format sources when done:",
    "Formatea las unidades de origen al acabar el volcado y la comprobación": "Format source drives after the dump and verification",
    "Rápido": "Quick",
    "Completo": "Full",
    "Apagar al acabar": "Shut down when done",
    "Apaga el ordenador al finalizar todas las tareas de ingesta": "Shut down the computer after all ingest tasks finish",
    "Archivo": "File",
    "Estado": "Status",
    "Destino": "Destination",
    "Carpeta footage:": "Footage folder:",
    "Cámara primero": "Camera first",
    "Fecha primero": "Date first",
    "Solo cámara": "Camera only",
    "Sin subcarpetas": "No subfolders",
    "Organización:": "Organization:",
    "Un solo día": "Single day",
    "Múltiples días": "Multiple days",
    "Sin fecha": "No date",
    "Duración:": "Duration:",
    "Usar fecha de metadatos:": "Use metadata date:",
    "Fecha:": "Date:",
    "Cambiar...": "Change...",
    "(sin definir)": "(not set)",
    "Ruta maestra:": "Master path:",
    "Seleccionar ruta maestra": "Select master path",
    "Guardar": "Save",
    "Establecer como predeterminado": "Set as default",
    "Valores guardados como predeterminados.": "Values saved as defaults.",
    "Cancelar": "Cancel",
    "Detección de cámara": "Camera detection",
    "Modo": "Mode",
    "Manual": "Manual",
    "Automático (próximamente)": "Automatic (coming soon)",
    "El modo automático estará disponible próximamente.": "Automatic mode will be available soon.",
    "Tiempo máximo de escaneo": "Maximum scan time",
    "Solo aplica al modo automático, disponible próximamente.": "Only applies to automatic mode, available soon.",
    "Detección de cámara actualizada.": "Camera detection updated.",
    "Puedes añadir, duplicar, renombrar o eliminar nombres.": "You can add, duplicate, rename or delete names.",
    "Puedes añadir, renombrar o eliminar nombres.": "You can add, rename or delete names.",
    "Buscar...": "Search...",
    "Añadir": "Add",
    "Nuevo nombre:": "New name:",
    "Renombrar": "Rename",
    "Eliminar": "Delete",
    "¿Eliminar '%1'?": "Delete '%1'?",
    "Añadir...": "Add...",
    "Renombrar...": "Rename...",
    "Duplicar": "Duplicate",
    "Cerrar": "Close",
    "Personalizar carpeta de footage": "Customize footage folder",
    "Personalizar contenedores de archivos": "Customize file containers",
    "Sin proyecto": "No project",
    "Selecciona un proyecto primero.": "Select a project first.",
    "Destinos de volcado": "Dump destinations",
    "Los archivos se repartirán entre estos destinos por orden. Cuando uno esté lleno se pasará al siguiente. Deja vacío para usar la ruta maestra del proyecto.": "Files will be split among these destinations in order. When one is full, it moves to the next. Leave empty to use the project master path.",
    "fecha": "date",
    "cámara": "camera",
    "Subir": "Move up",
    "Bajar": "Move down",
    "Seleccionar destino de volcado": "Select dump destination",
    "Destino de volcado": "Dump destination",
    "Etiqueta (opcional):": "Label (optional):",
    "-- Selecciona un proyecto --": "-- Select a project --",
    "Error": "Error",
    "No se pudieron cargar los proyectos: %1": "Could not load projects: %1",
    "Aviso": "Warning",
    "Proyecto #%1 no encontrado.": "Project #%1 not found.",
    "(sin ruta)": "(no path)",
    "Proyecto: %1": "Project: %1",
    "Nombre del proyecto:": "Project name:",
    "Descripción (opcional):": "Description (optional):",
    "Proyecto #%1 creado con sesión inicial.": "Project #%1 created with initial session.",
    "No se pudo crear el proyecto: %1": "Could not create the project: %1",
    "Nuevo nombre del proyecto:": "New project name:",
    "Proyecto renombrado a '%1'.": "Project renamed to '%1'.",
    "No se pudo renombrar el proyecto: %1": "Could not rename the project: %1",
    "Nombre del proyecto duplicado:": "Name of the duplicated project:",
    "Proyecto duplicado como '%1' (ID %2).": "Project duplicated as '%1' (ID %2).",
    "No se pudo duplicar el proyecto: %1": "Could not duplicate the project: %1",
    "Sin orígenes": "No sources",
    "No hay sesiones con rutas de origen válidas.": "There are no sessions with valid source paths.",
    "Ya en marcha": "Already running",
    "El monitoreo de la SD ya está activo.": "SD monitoring is already active.",
    "Procesando...": "Processing...",
    "Procesando %1 ruta(s): %2": "Processing %1 path(s): %2",
    "En progreso": "In progress",
    "Iniciar Ingesta": "Start Ingest",
    "Ingesta detenida por el usuario": "Ingest stopped by user",
    "Detenido": "Stopped",
    "Sin nombre": "No name",
    "Detectando...": "Detecting...",
    "Copiando...": "Copying...",
    "Procesando: %1": "Processing: %1",
    "Completado": "Completed",
    "%1 procesados": "%1 processed",
    "%1 pendientes": "%1 pending",
    "Ingesta completada: %1 procesados, %2 errores, %3 omitidos.": "Ingest complete: %1 processed, %2 errors, %3 skipped.",
    "formateo de orígenes": "source formatting",
    "apagado del equipo": "computer shutdown",
    "Acciones posteriores bloqueadas": "Post-ingest actions blocked",
    "Hay errores en la ingesta. Por seguridad, se han bloqueado las siguientes acciones:\n• %1": "There were errors during ingest. For safety, the following actions have been blocked:\n• %1",
    "Formatear orígenes": "Format sources",
    "El formateo de tarjetas solo está disponible en Windows.": "Card formatting is only available on Windows.",
    "No hay orígenes que formatear.": "There are no sources to format.",
    "completo": "full",
    "rápido": "quick",
    "Ninguno de los orígenes es una unidad extraíble. No se formateará nada.": "None of the sources is a removable drive. Nothing will be formatted.",
    "Se formatearán las unidades extraíbles (modo %1):": "Removable drives will be formatted (mode %1):",
    "\nSe omitirán (no son unidades extraíbles):": "\nWill be skipped (not removable drives):",
    "\n\n¿Continuar?": "\n\nContinue?",
    "Formateando...": "Formatting...",
    "Formatear": "Format",
    "No se pudo completar el formateo:\n%1": "Formatting could not be completed:\n%1",
    "Formateados %1/%2 con errores": "%1/%2 formatted with errors",
    "Formateados %1/%2.\nErrores:\n%3": "Formatted %1/%2.\nErrors:\n%3",
    "Orígenes formateados: %1/%2": "Sources formatted: %1/%2",
    "Orígenes formateados correctamente: %1/%2.": "Sources formatted successfully: %1/%2.",
    "Apagar ordenador": "Shut down computer",
    "Todas las tareas han finalizado. ¿Apagar el ordenador ahora?": "All tasks have finished. Shut down the computer now?",
    "Apagado programado.": "Shutdown scheduled.",
    "Apagar": "Shut down",
    "No se pudo programar el apagado:\n%1": "Could not schedule the shutdown:\n%1",
    "Renombrar cámara...": "Rename camera...",
    "Sin cámara": "No camera",
    "No se detectó cámara para renombrar.": "No camera was detected to rename.",
    "Renombrar cámara": "Rename camera",
    "Nuevo nombre para '%1':": "New name for '%1':",
    "Cámara renombrada: %1 → %2": "Camera renamed: %1 → %2",
    "Cámara desconocida detectada": "Unknown camera detected",
    "Se detectó '%1' sin identificar.\nIntroduce un nombre para el dispositivo:": "'%1' was detected but not identified.\nEnter a name for the device:",
    "Nombre de la cámara para este origen:": "Camera name for this source:",
    "Cámara: Sin nombre (manual)": "Camera: No name (manual)",
    "Cámara detectada: %1": "Camera detected: %1",
    "Escaneo de cámaras: %1 sesion(es) procesada(s).": "Camera scan: %1 session(s) processed.",
    "Cámara no detectada": "Camera not detected",
    "No se pudo detectar la cámara en %1.": "Could not detect the camera on %1.",
    "¿Qué nombre quieres darle a esta cámara?": "What name do you want to give this camera?",
    "Renombrar…": "Rename…",
    "Nombre de cámara": "Camera name",
    "Introduce el nombre de la cámara:": "Enter the camera name:",
    "Cámara: %1": "Camera: %1",
    "Cámara: Sin nombre": "Camera: No name",
    "Origen asignado a sesión #%1": "Source assigned to session #%1",
    "Sesión auto creada para %1": "Auto session created for %1",
    "Sesión de %1 eliminada.": "Session for %1 deleted.",
    "(Sin sesiones)": "(No sessions)",
    "Origen: %1": "Source: %1",
    "Origen: sin origen (no se ejecutará)": "Source: no source (will not run)",
    "Nueva Sesión manual": "New Manual Session",
    "Nombre de la sesión:": "Session name:",
    "Sesión manual '%1' creada (ID: %2)": "Manual session '%1' created (ID: %2)",
    "¿Eliminar la sesión #%1 y todos sus archivos?\nEsta acción no se puede deshacer.": "Delete session #%1 and all its files?\nThis action cannot be undone.",
    "Sesión #%1 eliminada.": "Session #%1 deleted.",
    "Seleccionar destino de sesión": "Select session destination",
    "Seleccionar origen de sesión": "Select session source",
    "&Archivo": "&File",
    "&Nuevo Proyecto...": "&New Project...",
    "&Recargar proyectos": "&Reload projects",
    "&Eliminar todos los proyectos...": "&Delete all projects...",
    "&Salir": "&Quit",
    "&Rutas": "&Routes",
    "Seleccionar &origen (SD)...": "Select &source (SD)...",
    "Seleccionar &destino del proyecto...": "Select project &destination...",
    "Auto-detectar &unidades extraíbles al inicio": "Auto-detect &removable drives at startup",
    "&Detectar unidades extraíbles ahora": "&Detect removable drives now",
    "Abrir carpeta &datos...": "Open &data folder...",
    "Gestionar &destinos de volcado...": "Manage &dump destinations...",
    "&Detección": "&Detection",
    "Configurar detección de &cámara...": "Configure &camera detection...",
    "Detectar &información de tarjeta SD...": "Detect &SD card info...",
    "&Personalizado": "&Customize",
    "Personalizar &carpeta de footage...": "Customize &footage folder...",
    "Personalizar &contenedores de archivos...": "Customize &file containers...",
    "&Vista": "&View",
    "Tema": "Theme",
    "Acento": "Accent",
    "Fondo de trigo": "Wheat background",
    "Oscuro": "Dark",
    "Claro": "Light",
    "Neutro": "Neutral",
    "Verde": "Green",
    "Azul": "Blue",
    "Rosa": "Pink",
    "Morado": "Purple",
    "Ámbar": "Amber",
    "A&yuda": "&Help",
    "&Búsqueda de actualizaciones...": "&Check for updates...",
    "&Acerca de...": "&About...",
    "&Idioma": "&Language",
    "Idioma": "Language",
    "Reinicia la aplicación para aplicar el idioma.": "Restart the app to apply the language.",
    "Seleccionar carpeta de la Tarjeta SD": "Select SD Card folder",
    "Selecciona o crea un proyecto antes de cambiar su destino.": "Select or create a project before changing its destination.",
    "Seleccionar carpeta maestra del proyecto": "Select project master folder",
    "Destino maestro actualizado: %1": "Master destination updated: %1",
    "No se pudo actualizar el destino: %1": "Could not update the destination: %1",
    "Selecciona un proyecto para eliminar.": "Select a project to delete.",
    "Confirmar eliminación": "Confirm deletion",
    "¿Eliminar el proyecto #%1 y todos sus datos?\nEsta acción no se puede deshacer.": "Delete project #%1 and all its data?\nThis action cannot be undone.",
    "Eliminado": "Deleted",
    "Proyecto eliminado correctamente.": "Project deleted successfully.",
    "Error al eliminar el proyecto: %1": "Error deleting the project: %1",
    "Sin proyectos": "No projects",
    "No hay proyectos para eliminar.": "There are no projects to delete.",
    "Eliminar todos los proyectos": "Delete all projects",
    "¿Eliminar los %1 proyectos y todos sus datos?\nEsta acción no se puede deshacer.": "Delete the %1 projects and all their data?\nThis action cannot be undone.",
    "Eliminados": "Deleted",
    "Todos los proyectos han sido eliminados.": "All projects have been deleted.",
    "Error al eliminar los proyectos: %1": "Error deleting the projects: %1",
    "Acerca de CosechaMedia": "About CosechaMedia",
    "Herramienta de ingesta de tarjetas SD para producción audiovisual.": "SD card ingest tool for audiovisual production.",
    "El Modo guiado para volcados rápidos estará disponible próximamente.": "Guided mode for quick dumps will be available soon.",
    "Búsqueda de actualizaciones": "Check for updates",
    "La búsqueda de actualizaciones estará disponible próximamente.": "Update checking will be available soon.",
    "Sin origen": "No source",
    "Selecciona o añade una ruta de tarjeta SD primero.": "Select or add an SD card path first.",
    "Marca: %1": "Brand: %1",
    "Modelo: %1": "Model: %1",
    "Serie: %1": "Serial: %1",
    "Capacidad: %1 GB": "Capacity: %1 GB",
    "Sistema: %1": "File system: %1",
    "Uso: %1%": "Usage: %1%",
    "Errores: %1": "Errors: %1",
    "No se pudo detectar información de la tarjeta.": "Could not detect card information.",
    "Información de Tarjeta SD": "SD Card Information",
    "No se detectaron unidades extraíbles.": "No removable drives detected.",
    "Auto-detect: %1 unidad(es) añadida(s).": "Auto-detect: %1 drive(s) added.",
    "Auto-detect: ninguna unidad nueva.": "Auto-detect: no new drives.",
    "Sin ingesta": "No ingest",
    "Realiza una ingesta primero.": "Run an ingest first.",
    "Reorganizar": "Reorganize",
    "¿Reorganizar archivos en 'Unknown_Camera' detectando su cámara por metadatos?": "Reorganize files in 'Unknown_Camera' by detecting their camera via metadata?",
    "Reorganizando...": "Reorganizing...",
    "No se pudo reorganizar:\n%1": "Could not reorganize:\n%1",
    "Hecho": "Done",
    "Archivos reorganizados.": "Files reorganized.",
    "Proxies": "Proxies",
    "No se encontraron clips de video en la ingesta.": "No video clips found in the ingest.",
    "Generar proxies %1p para %2 clips de video?": "Generate %1p proxies for %2 video clips?",
    "Generando proxies...": "Generating proxies...",
    "No se pudieron generar los proxies:\n%1": "Could not generate the proxies:\n%1",
    "Proxies generados: %1": "Proxies generated: %1",
    "Nuevo Proyecto": "New Project",
    "Nombre del Proyecto": "Project Name",
    "Ej: Rodaje_Cine_01": "E.g. Shoot_Film_01",
    "Descripción (Opcional)": "Description (Optional)",
    "Breve descripción del proyecto...": "Brief project description...",
    "Ruta de Destino": "Destination Path",
    "Ej: H:/Produccion/Proyectos": "E.g. H:/Production/Projects",
    "Duración": "Duration",
    "Todos los archivos pertenecen al mismo día": "All files belong to the same day",
    "Los archivos se organizarán por fecha de rodaje": "Files will be organized by shoot date",
    "No se usará fecha para organizar los archivos": "No date will be used to organize the files",
    "Organización": "Organization",
    "Cámara primero (Cámara/Fecha)": "Camera first (Camera/Date)",
    "Fecha primero (Fecha/Cámara)": "Date first (Date/Camera)",
    "Solo por cámara": "Camera only",
    "Usar fecha de metadatos": "Use metadata date",
    "Usar las fechas de los archivos en lugar de la fecha manual": "Use file dates instead of the manual date",
    "Crear Proyecto": "Create Project",
    "Debes poner un nombre y una ruta de destino.": "You must provide a name and a destination path.",
    "No se pudo guardar el proyecto: %1": "Could not save the project: %1",
    "Solo se admiten letras de unidad de Windows en este momento.": "Only Windows drive letters are supported at the moment.",
    "Formateando %1 (%2/%3)...": "Formatting %1 (%2/%3)...",
    "Proxy %1/%2: %3": "Proxy %1/%2: %3",
    "Reorganizando ingesta %1/%2...": "Reorganizing ingest %1/%2...",
}


def _escape(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def _serialize_message(msg, missing):
    source = msg.findtext("source")
    translation = TRANSLATIONS.get(source, missing)
    lines = ["    <message>"]
    for loc in msg.findall("location"):
        fn = loc.get("filename")
        ln = loc.get("line", "")
        lines.append(f'        <location filename="{_escape(fn)}" line="{ln}"/>')
    lines.append(f"        <source>{_escape(source)}</source>")
    if translation is None:
        lines.append('        <translation type="unfinished"></translation>')
    else:
        lines.append(f"        <translation>{_escape(translation)}</translation>")
    lines.append("    </message>")
    return "\n".join(lines)


def main():
    tree = ET.parse(TS_PATH)
    root = tree.getroot()
    contexts = []
    missing = []
    for context in root.findall("context"):
        name = context.findtext("name") or ""
        messages = []
        for msg in context.findall("message"):
            source = msg.findtext("source")
            if source is not None and source not in TRANSLATIONS:
                missing.append(source)
            messages.append(_serialize_message(msg, None))
        contexts.append((name, messages))

    if missing:
        print("MISSING TRANSLATIONS:")
        for m in sorted(set(missing)):
            print("  -", repr(m))
        sys.exit(1)

    parts = ['<?xml version="1.0" encoding="utf-8"?>', "<!DOCTYPE TS>",
             '<TS version="2.1" language="en_US">']
    for name, messages in contexts:
        parts.append("<context>")
        parts.append(f"    <name>{_escape(name)}</name>")
        parts.extend(messages)
        parts.append("</context>")
    parts.append("</TS>")
    with open(TS_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print("OK: translations written to", TS_PATH)


if __name__ == "__main__":
    main()
